name: flutter_rss
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  webfeed: ^0.4.2
  intl: ^0.16.1
  webview_flutter: ^0.3.21
  url_launcher: ^5.4.5
  flustars: ^0.3.1
  sqflite: ^1.3.0
  flutter_easyloading: ^1.1.4   # toast/loading/process/success/er
  path_provider: ^1.6.7
  provider: ^4.0.5
  package_info: ^0.4.0+17
  get_it: ^4.0.2
  splashscreen: ^1.2.0
  flutter_widget_from_html: ^0.4.0-rc.2020043001
  cached_network_image: ^2.1.0+1
  extended_image: ^0.7.3+1
  permission_handler: '^4.2.0+hotfix.2'
  share: ^0.6.4
  image_gallery_saver: ^1.2.2
  transparent_image: ^1.0.0
  flutter_html: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
flutter_intl:
  enabled: true
