name: flutter_rss
description: A new Flutter application.

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  webfeed: ^0.4.2
  intl: ^0.16.1
  webview_flutter: ^0.3.20+2
  url_launcher: ^5.4.5
  flustars: ^0.2.6+1
  sqflite: ^1.3.0
  flutter_easyloading: ^1.1.3   # toast/loading/process/success/error
  path_provider: ^1.6.7
  provider: ^4.0.5
  package_info: ^0.4.0+14
  get_it: 1.0.3+2
  flutter_html: ^0.11.1
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
flutter_intl:
  enabled: true
